title: Analytics Engineering Mailing List Archive

titles_from_headings:
  enabled: true
  strip_title: true

header_pages:
  - 2024/thread.md
  
remote_theme: jekyll/minima
minima:
  skin: solarized
